[package]
name = "pena-demo-actixweb"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
shuttle-service = { version = "0.11.0", features = ["web-actix-web"] }
actix-web = "4.3.1"
actix-files = "0.6"
actix-rt = "1.1.1"
